# W5 is the oscillator pin
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

# create clock
create_clock -period  3 -name clock_object [get_ports clk]

# outputs
set_property PACKAGE_PIN V14      [get_ports {o_rand_output[0]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {o_rand_output[0]}]
set_property PACKAGE_PIN U14      [get_ports {o_rand_output[1]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {o_rand_output[1]}]
set_property PACKAGE_PIN U15      [get_ports {o_rand_output[2]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {o_rand_output[2]}]
set_property PACKAGE_PIN W18      [get_ports {o_rand_output[3]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {o_rand_output[3]}]
set_property PACKAGE_PIN V19      [get_ports {o_rand_output[4]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {o_rand_output[4]}]
set_property PACKAGE_PIN U19      [get_ports {o_rand_output[5]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {o_rand_output[5]}]
set_property PACKAGE_PIN E19      [get_ports {o_rand_output[6]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {o_rand_output[6]}]
set_property PACKAGE_PIN U16      [get_ports {o_rand_output[7]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {o_rand_output[7]}]

# inputs
set_property PACKAGE_PIN V17 [get_ports {i_read_input[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_read_input[0]}]
set_property PACKAGE_PIN V16 [get_ports {i_read_input[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_read_input[1]}]
set_property PACKAGE_PIN W16 [get_ports {i_read_input[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_read_input[2]}]
set_property PACKAGE_PIN W17 [get_ports {i_read_input[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_read_input[3]}]
set_property PACKAGE_PIN W15 [get_ports {i_read_input[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_read_input[4]}]
set_property PACKAGE_PIN V15 [get_ports {i_read_input[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_read_input[5]}]
set_property PACKAGE_PIN W14 [get_ports {i_read_input[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_read_input[6]}]
set_property PACKAGE_PIN W13 [get_ports {i_read_input[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_read_input[7]}]
set_property PACKAGE_PIN V2 [get_ports {i_read_input[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_read_input[8]}]
set_property PACKAGE_PIN T3 [get_ports {i_read_input[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_read_input[9]}]
set_property PACKAGE_PIN T2 [get_ports {i_read_input[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_read_input[10]}]
set_property PACKAGE_PIN R3 [get_ports {i_read_input[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_read_input[11]}]
